name: Wisecow CI/CD with Kind

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t wisecow:latest .

      # 4. Install Kind & kubectl
      - name: Set up Kind 
        uses: helm/kind-action@v1.8.0
        with:
          version: v0.20.0
          node_image: kindest/node:v1.27.3
          cluster_name: kind   

      # 5. Load Docker image into Kind
      - name: Load Docker image into Kind
        run: kind load docker-image wisecow:latest --name kind  

      # 6. Export kubeconfig for kubectl
      - name: Export kubeconfig
        run: |
          kind get kubeconfig --name kind > $HOME/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
          kubectl wait --for=condition=Ready nodes --all --timeout=120s

      # 7. Deploy Wisecow app
      - name: Deploy Wisecow
        run: |
          kubectl apply -f k8s/deployment.yaml --validate=false --kubeconfig $HOME/.kube/config
          kubectl apply -f k8s/service.yaml --validate=false --kubeconfig $HOME/.kube/config
          kubectl rollout status deployment/wisecow-deployment --timeout=120s --kubeconfig $HOME/.kube/config

      # 8. Verify deployment
      - name: Verify Pods
        run: |
          kubectl get pods -o wide

